### PR TITLE
Updates to latest wazero and fixes memory access

### PR DESCRIPTION
**Pull request by codefromthecrypt**
This updates to latest and rejigs how memory is passed back from TinyGo
to normal Go. This also added build steps. Enjoy!

Screen Shot 2022-04-19 at 7 37 09 PM

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
ps I added a commit to simplify the return into a single value while documenting the risk. Since other projects currently return pointers and immediately read them, I think it is relatively safe, especially in a loop with one goroutine. This is easier to read and simpler to explain than manual pointer management. Meanwhile hopefully we can get some clarification in https://github.com/tinygo-org/tinygo/issues/2787

**Comment by codefromthecrypt** [comment]
fyi I don't mean to be a nuisance, so will close this in a week if not merged. thanks for trying wazero!

**Comment by efejjota** [comment]
Hello @codefromthecrypt 
And thank you for all the hard work you put into this. I'm sorry for not participating more actively.
I have been posponing working on this little experiment I did and didn't mean to disregard your efforts. 
Merging it now.
Thank you for your hard work with Wazero.

**Comment by codefromthecrypt** [comment]
glad this was helpful! probably it was a good postponement anyway as we had changed a lot since :D

**Pull request merged**
